name: Sonar

on:
  push:
    branches: [ sonar ]
  pull_request:
    branches: [ sonar ]
      
jobs:
  build:
  
      runs-on: windows-latest
      
      steps:
      - name: sonar-scanner-install
        run: |
          Invoke-RestMethod -Uri https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/5.5.3.43281/sonar-scanner-msbuild-5.5.3.43281-net46.zip -OutFile sonar-scanner-msbuild-5.5.3.43281-net46.zip
          Expand-Archive .\sonar-scanner-msbuild-5.5.3.43281-net46.zip
          ls
          
      - name: repo
        uses: actions/checkout@v1
        
      - name: sonar-scanner-run
        run: |
          ls
