name: Sonar

on:
  push:
    branches: [ Scanner ]
  pull_request:
    branches: [ Scanner ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
     
      - name: Install Sonar global tool
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Build
        run: |
          dotnet sonarscanner begin /k:"tring" /d:sonar.host.url="https://sonarqube.devsoftengi.space" /d:sonar.login="09c76e3588c0c06e1f84355d1c44d8c82a0e7f7a"
          dotnet build App/App.sln
          dotnet sonarscanner end /d:sonar.login="09c76e3588c0c06e1f84355d1c44d8c82a0e7f7a"